"""création tables user destination reservation activitylog

Revision ID: 35a6b1d29f34
Revises: b10ee2a84d75
Create Date: 2026-02-04 19:00:37.115357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a6b1d29f34'
down_revision = 'b10ee2a84d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('date_depart')
        batch_op.drop_column('date_retour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_retour', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('date_depart', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
