"""Initial migration

Revision ID: 48bf9da72233
Revises: 
Create Date: 2026-01-25 12:51:10.512074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48bf9da72233'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('destinations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('continent', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avgCostUSD', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bestSeason', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('avgRating', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('annualVisitors', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unescoSite', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('photoURL', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
