"""Mise à jour suite au changement de modèles

Revision ID: 70b6aff16552
Revises: 
Create Date: 2026-03-31 01:28:47.532190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70b6aff16552'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('bestSeason',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('avgRating',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('annualVisitors',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('unescoSite',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('avgCostUSD',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('avgCostUSD',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('unescoSite',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('annualVisitors',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('avgRating',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bestSeason',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('Description')

    # ### end Alembic commands ###
