"""clean migration

Revision ID: bb58a8d43dff
Revises: 
Create Date: 2026-04-11 01:50:52.169598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb58a8d43dff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('destination_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reservation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'destinations', ['destination_id'], ['id'])
        batch_op.create_foreign_key(None, 'reservations', ['reservation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reservation_id')
        batch_op.drop_column('destination_name')
        batch_op.drop_column('destination_id')
        batch_op.drop_column('contact_type')

    # ### end Alembic commands ###
