"""Initialisation propre avec enum search

Revision ID: d5da2703118a
Revises: 
Create Date: 2026-04-07 22:36:46.763138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5da2703118a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relance_logs')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('priority', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sentiment', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ai_summary', mysql.TEXT(), nullable=True),
    sa.Column('suggested_reply', mysql.TEXT(), nullable=True),
    sa.Column('auto_email_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('relance_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email_body', mysql.TEXT(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('relance_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
